### ISSUE TITLE
error to compile 

### ISSUE THREAD

**Issue by andremoraes** [DevExpress-Examples/winui-gridcontrol-export-grid-data#1]
I've trying to set the program to be .net 5 or 6.... about the same error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package DevExpress.WinUI 21.2.4 is not compatible with net6.0 (.NETCoreApp,Version=v6.0). Package DevExpress.WinUI 21.2.4 supports: net6.0-windows10.0.18362 (.NETCoreApp,Version=v6.0)	ExportGridControl	C:\Users\andre.moraes\Downloads\winui-gridcontrol-export-grid-data-21.2.4-\CS\ExportGridControl\ExportGridControl\ExportGridControl.csproj	1

**Comment by DmitryRomenskiy** [comment]
@andremoraes Please accept my apologies for the late reply. We recommend contacting us through the [Support Center](https://supportcenter.devexpress.com/ticket/list) to receive technical support. Feel free to create a ticket for this issue if it still occurs.
